version: "3"
services:
  cassandra:
    image: docker.io/bitnami/cassandra:3-debian-10
    volumes:
      - cassandra_data:/bitnami
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USER=kong
      - CASSANDRA_PASSWORD=kong
      - CASSANDRA_PASSWORD_SEEDER=yes
  kong:
    image: docker.io/bitnami/kong:2-debian-10
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    environment:
      - KONG_MIGRATE=yes
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_CASSANDRA_PASSWORD=kong

  konga:
    image: pantsel/konga:latest
    depends_on:
      - kong
    logging:
      options:
        max-size: "50m"
    environment:
      - TOKEN_SECRET=ahfdjgjgf79JKLFHJKh978953kgdfjkl
      - NODE_ENV=development
    ports:
      - "1337:1337"

volumes:
  cassandra_data:
    driver: local