version: "3.7"
services:

  #jenkins:
  #  image: jenkins/jenkins:lts
  #  container_name: jenkins
  #  privileged: true
  #  user: root
  #  volumes:
  #    - ./extra/jenkins_configuration:/var/jenkins_home
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  ports:
  #    - 8082:8080
  #    - 50000:50000


  db:
    container_name: pg
    image: postgres:9.6.24
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bankaccount
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:6.2.6-bullseye
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  app-network:
    driver: bridge


volumes:
  pgdata: