server:
  port: 8081

springdoc:
  packagesToScan: me.com.neves.bankaccount.endpoint
  api-docs:
    path: /api-docs
  server:
    url: http://localhost:8081/
  version: v1
  swagger-ui:
    operationsSorter: method
    tags-sorter: alpha
    default-model-expand-depth: -1
    doc-expansion: none
    disable-swagger-default-url: true
    use-root-path: true

info:
  app:
    title: Neves bank account
